# Generated by Django 6.0.3 on 2026-03-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='reports/')),
                ('location', models.CharField(max_length=255)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Validated', 'Validated'), ('Rejected', 'Rejected'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
            ],
        ),
    ]
